// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgH1AecasJUkCK4ec_fjcvm0FoAIFRL5o',
    appId: '1:787956522800:web:f4df1d0c6780fc0eefb2f5',
    messagingSenderId: '787956522800',
    projectId: 'portfolio-1ede2',
    authDomain: 'portfolio-1ede2.firebaseapp.com',
    storageBucket: 'portfolio-1ede2.appspot.com',
    measurementId: 'G-Q3B1DCX334',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgsfEyV1uOLNivMQfouHxmEcE113l_Ifk',
    appId: '1:787956522800:android:bcae19f14acc1b91efb2f5',
    messagingSenderId: '787956522800',
    projectId: 'portfolio-1ede2',
    storageBucket: 'portfolio-1ede2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdX756wSfrou0H0reUSK6AwJ0DTJ5TUSg',
    appId: '1:787956522800:ios:7423811d48ae73baefb2f5',
    messagingSenderId: '787956522800',
    projectId: 'portfolio-1ede2',
    storageBucket: 'portfolio-1ede2.appspot.com',
    iosBundleId: 'com.johcode.portfolio.portafolio',
  );

}